# Generated by protoc-gen-mojo from echo.proto. Do not edit.

"""Generated protobuf messages and gRPC stubs from `echo.proto`.

Regenerate with tools/protoc-gen-mojo; do not edit by hand.
"""

from proto import (
    WIRE_FIXED32,
    WIRE_FIXED64,
    WIRE_LEN,
    WIRE_VARINT,
    ProtoMessage,
    WireReader,
    WireWriter,
    zigzag_encode32,
    zigzag_encode64,
)
from proto import (
    ProtoJsonMessage,
    ProtoJsonReader,
    ProtoJsonWriter,
)
from grpc import (
    BidiStreamingCall,
    ClientStreamingCall,
    GrpcChannel,
    PollingServer,
    Server,
    ServerCall,
    ServerContext,
    ServerStreamingCall,
    ReflectionRegistry,
)


struct EchoRequest(Copyable, Defaultable, Movable, ProtoMessage, ProtoJsonMessage):
    """Generated from the `EchoRequest` protobuf message."""

    var message: String
    """Field `message` (number 1)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.message = String()
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.message.byte_length() != 0:
            writer.string_field(1, self.message)
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.message = reader.string_value()
            else:
                reader.capture_field(field, wire_type, self._unknown)

    def encode_json_to(
        self, mut writer: ProtoJsonWriter
    ) raises:
        """Writes this message using the proto3 JSON mapping.

        Args:
            writer: Destination JSON writer.

        Raises:
            Error: If a field cannot be written as valid JSON.
        """
        writer.begin_object()
        if self.message.byte_length() != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("message", "message")
            writer.string_value(self.message)
        writer.end_object()

    def merge_json_from(
        mut self, mut reader: ProtoJsonReader
    ) raises:
        """Merges fields from one proto3 JSON object.

        Args:
            reader: Source JSON reader.

        Raises:
            Error: If the input is not valid proto3 JSON.
        """
        var seen_1 = False
        reader.begin_object()
        while True:
            var next_field = reader.next_field()
            if not next_field:
                break
            var field_name = next_field.value()
            if field_name == "message" or field_name == "message":
                if seen_1:
                    raise Error("proto json: duplicate field message")
                seen_1 = True
                if reader.read_null():
                    self.message = String()
                else:
                    self.message = reader.string_value()
            else:
                reader.skip_unknown_value()


struct EchoResponse(Copyable, Defaultable, Movable, ProtoMessage, ProtoJsonMessage):
    """Generated from the `EchoResponse` protobuf message."""

    var message: String
    """Field `message` (number 1)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.message = String()
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.message.byte_length() != 0:
            writer.string_field(1, self.message)
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.message = reader.string_value()
            else:
                reader.capture_field(field, wire_type, self._unknown)

    def encode_json_to(
        self, mut writer: ProtoJsonWriter
    ) raises:
        """Writes this message using the proto3 JSON mapping.

        Args:
            writer: Destination JSON writer.

        Raises:
            Error: If a field cannot be written as valid JSON.
        """
        writer.begin_object()
        if self.message.byte_length() != 0 or writer.options.always_print_fields_with_no_presence:
            writer.field("message", "message")
            writer.string_value(self.message)
        writer.end_object()

    def merge_json_from(
        mut self, mut reader: ProtoJsonReader
    ) raises:
        """Merges fields from one proto3 JSON object.

        Args:
            reader: Source JSON reader.

        Raises:
            Error: If the input is not valid proto3 JSON.
        """
        var seen_1 = False
        reader.begin_object()
        while True:
            var next_field = reader.next_field()
            if not next_field:
                break
            var field_name = next_field.value()
            if field_name == "message" or field_name == "message":
                if seen_1:
                    raise Error("proto json: duplicate field message")
                seen_1 = True
                if reader.read_null():
                    self.message = String()
                else:
                    self.message = reader.string_value()
            else:
                reader.skip_unknown_value()


comptime ECHO_SAY_PATH = "/echo.Echo/Say"
"""Request path of the `echo.Echo/Say` method."""
comptime ECHO_SPLIT_PATH = "/echo.Echo/Split"
"""Request path of the `echo.Echo/Split` method."""
comptime ECHO_JOIN_PATH = "/echo.Echo/Join"
"""Request path of the `echo.Echo/Join` method."""
comptime ECHO_CHAT_PATH = "/echo.Echo/Chat"
"""Request path of the `echo.Echo/Chat` method."""


@fieldwise_init
struct EchoClient(Movable):
    """Generated client for the `echo.Echo` service."""

    var channel: GrpcChannel
    """The underlying channel; usable directly for low-level streaming."""

    @staticmethod
    def connect(host: StringSpan, port: UInt16) raises -> EchoClient:
        """Connects a new client over plaintext HTTP/2 (h2c).

        Args:
            host: Hostname or numeric IP of the server.
            port: TCP port of the server.

        Returns:
            A connected client.

        Raises:
            Error: If resolution or connection fails.
        """
        return EchoClient(channel=GrpcChannel.connect(host, port))

    def say(mut self, request: EchoRequest, *, timeout_ns: Int64 = 0) raises -> EchoResponse:
        """Calls the unary `Say` method.

        Args:
            request: The request message.
            timeout_ns: Call deadline in nanoseconds; 0 means none.

        Returns:
            The response message.

        Raises:
            Error: If the call ends with a non-OK status.
        """
        return self.channel.unary[EchoRequest, EchoResponse](
            ECHO_SAY_PATH, request, timeout_ns=timeout_ns
        )

    def split(mut self, request: EchoRequest, *, timeout_ns: Int64 = 0) raises -> ServerStreamingCall[EchoResponse]:
        """Starts the server-streaming `Split` method.

        Receive with `call.recv()` until it returns `None`,
        then call `call.finish()`.

        Args:
            request: The request message.
            timeout_ns: Call deadline in nanoseconds; 0 means none.

        Returns:
            A typed handle for the response stream.

        Raises:
            Error: If the call cannot be started.
        """
        return ServerStreamingCall[EchoResponse].start[EchoRequest](
            self.channel, ECHO_SPLIT_PATH, request, timeout_ns=timeout_ns
        )

    def join(mut self, *, timeout_ns: Int64 = 0) raises -> ClientStreamingCall[EchoRequest, EchoResponse]:
        """Starts the client-streaming `Join` method.

        Send with `call.send(msg)`, then `call.finish()` to
        half-close and read the response.

        Args:
            timeout_ns: Call deadline in nanoseconds; 0 means none.

        Returns:
            A typed handle for the request stream.

        Raises:
            Error: If the call cannot be started.
        """
        return ClientStreamingCall[EchoRequest, EchoResponse].start(
            self.channel, ECHO_JOIN_PATH, timeout_ns=timeout_ns
        )

    def chat(mut self, *, timeout_ns: Int64 = 0) raises -> BidiStreamingCall[EchoRequest, EchoResponse]:
        """Starts the bidirectional `Chat` method.

        Exchange with `call.send` and `call.recv` (ping-pong
        style), half-close with `call.close_send()`, then
        `call.finish()`.

        Args:
            timeout_ns: Call deadline in nanoseconds; 0 means none.

        Returns:
            A typed handle for both streams.

        Raises:
            Error: If the call cannot be started.
        """
        return BidiStreamingCall[EchoRequest, EchoResponse].start(
            self.channel, ECHO_CHAT_PATH, timeout_ns=timeout_ns
        )

    def close(mut self):
        """Closes the underlying connection."""
        self.channel.close()


def add_echo_service[
    say: def (EchoRequest, mut ServerContext) raises thin -> EchoResponse,
    split: def (EchoRequest, mut ServerContext, mut ServerCall) raises thin -> None,
    join: def (mut ServerContext, mut ServerCall) raises thin -> EchoResponse,
    chat: def (mut ServerContext, mut ServerCall) raises thin -> None,
](mut server: Server):
    """Registers `echo.Echo` handlers on a server.

    Parameters:
        say: Handler for the `Say` method.
        split: Handler for the `Split` method.
        join: Handler for the `Join` method.
        chat: Handler for the `Chat` method.

    Args:
        server: The server to register the handlers on.
    """
    server.register_unary[say](ECHO_SAY_PATH)
    server.register_server_streaming[split](ECHO_SPLIT_PATH)
    server.register_client_streaming[join](ECHO_JOIN_PATH)
    server.register_bidi[chat](ECHO_CHAT_PATH)


def add_echo_polling_service[
    say: def (EchoRequest, mut ServerContext) raises thin -> EchoResponse,
    split: def (EchoRequest, mut ServerContext, mut ServerCall) raises thin -> None,
    join: def (mut ServerContext, mut ServerCall) raises thin -> EchoResponse,
    chat: def (mut ServerContext, mut ServerCall) raises thin -> None,
](mut server: PollingServer) raises:
    """Registers `echo.Echo` handlers on a PollingServer.

    Parameters:
        say: Handler for the `Say` method.
        split: Handler for the `Split` method.
        join: Handler for the `Join` method.
        chat: Handler for the `Chat` method.

    Args:
        server: The polling server to register the handlers on.
    """
    server.register_unary[say](ECHO_SAY_PATH)
    server.register_server_streaming[split](ECHO_SPLIT_PATH)
    server.register_client_streaming[join](ECHO_JOIN_PATH)
    server.register_bidi[chat](ECHO_CHAT_PATH)


def echo_pb_file_descriptor_proto() -> List[Byte]:
    """Serialized `FileDescriptorProto` for `echo.proto`."""
    var out: List[Byte] = [
        10, 10, 101, 99, 104, 111, 46, 112, 114, 111, 116, 111, 18, 4, 101, 99,
        104, 111, 34, 39, 10, 11, 69, 99, 104, 111, 82, 101, 113, 117, 101, 115,
        116, 18, 24, 10, 7, 109, 101, 115, 115, 97, 103, 101, 24, 1, 32, 1,
        40, 9, 82, 7, 109, 101, 115, 115, 97, 103, 101, 34, 40, 10, 12, 69,
        99, 104, 111, 82, 101, 115, 112, 111, 110, 115, 101, 18, 24, 10, 7, 109,
        101, 115, 115, 97, 103, 101, 24, 1, 32, 1, 40, 9, 82, 7, 109, 101,
        115, 115, 97, 103, 101, 50, 202, 1, 10, 4, 69, 99, 104, 111, 18, 44,
        10, 3, 83, 97, 121, 18, 17, 46, 101, 99, 104, 111, 46, 69, 99, 104,
        111, 82, 101, 113, 117, 101, 115, 116, 26, 18, 46, 101, 99, 104, 111, 46,
        69, 99, 104, 111, 82, 101, 115, 112, 111, 110, 115, 101, 18, 48, 10, 5,
        83, 112, 108, 105, 116, 18, 17, 46, 101, 99, 104, 111, 46, 69, 99, 104,
        111, 82, 101, 113, 117, 101, 115, 116, 26, 18, 46, 101, 99, 104, 111, 46,
        69, 99, 104, 111, 82, 101, 115, 112, 111, 110, 115, 101, 48, 1, 18, 47,
        10, 4, 74, 111, 105, 110, 18, 17, 46, 101, 99, 104, 111, 46, 69, 99,
        104, 111, 82, 101, 113, 117, 101, 115, 116, 26, 18, 46, 101, 99, 104, 111,
        46, 69, 99, 104, 111, 82, 101, 115, 112, 111, 110, 115, 101, 40, 1, 18,
        49, 10, 4, 67, 104, 97, 116, 18, 17, 46, 101, 99, 104, 111, 46, 69,
        99, 104, 111, 82, 101, 113, 117, 101, 115, 116, 26, 18, 46, 101, 99, 104,
        111, 46, 69, 99, 104, 111, 82, 101, 115, 112, 111, 110, 115, 101, 40, 1,
        48, 1, 98, 6, 112, 114, 111, 116, 111, 51,
    ]
    return out^

def echo_pb_proto_name() -> String:
    """Filename of `echo.proto` for gRPC reflection."""
    return String("echo.proto")

def echo_pb_reflection_symbols() -> List[String]:
    """Fully-qualified symbols declared in `echo.proto`."""
    var symbols: List[String] = [
        String("echo.EchoRequest"),
        String("echo.EchoResponse"),
        String("echo.Echo"),
        String("echo.Echo.Say"),
        String("echo.Echo.Split"),
        String("echo.Echo.Join"),
        String("echo.Echo.Chat"),
    ]
    return symbols^

def add_echo_pb_file_descriptor(mut registry: ReflectionRegistry) raises:
    """Registers `echo.proto` with a reflection registry."""
    registry.add_file(
        echo_pb_proto_name(),
        echo_pb_file_descriptor_proto(),
        echo_pb_reflection_symbols(),
    )
    registry.add_service(String("echo.Echo"))
