# Generated by protoc-gen-mojo from empty.proto. Do not edit.

"""Generated protobuf messages from `empty.proto`.

Regenerate with tools/protoc-gen-mojo; do not edit by hand.
"""

from proto import (
    WIRE_FIXED32,
    WIRE_FIXED64,
    WIRE_LEN,
    WIRE_VARINT,
    ProtoMessage,
    WireReader,
    WireWriter,
    zigzag_encode32,
    zigzag_encode64,
)
from proto import (
    ProtoJsonMessage,
    ProtoJsonReader,
    ProtoJsonWriter,
)


struct Empty(Copyable, Defaultable, Movable, ProtoMessage, ProtoJsonMessage):
    """Generated from the `Empty` protobuf message."""

    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""
    def __init__(out self):
        """Initializes an empty message."""
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Args:
            writer: Destination wire-format writer.
        """
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            reader.capture_field(tag[0], tag[1], self._unknown)

    def encode_json_to(
        self, mut writer: ProtoJsonWriter
    ) raises:
        """Writes this message using the proto3 JSON mapping.

        Args:
            writer: Destination JSON writer.

        Raises:
            Error: If a field cannot be written as valid JSON.
        """
        writer.begin_object()
        writer.end_object()

    def merge_json_from(
        mut self, mut reader: ProtoJsonReader
    ) raises:
        """Merges fields from one proto3 JSON object.

        Args:
            reader: Source JSON reader.

        Raises:
            Error: If the input is not valid proto3 JSON.
        """
        reader.begin_object()
        while True:
            var next_field = reader.next_field()
            if not next_field:
                break
            reader.skip_unknown_value()


def empty_pb_file_descriptor_proto() -> List[Byte]:
    """Serialized `FileDescriptorProto` for `empty.proto`."""
    var out: List[Byte] = [
        10, 11, 101, 109, 112, 116, 121, 46, 112, 114, 111, 116, 111, 18, 12, 103,
        114, 112, 99, 46, 116, 101, 115, 116, 105, 110, 103, 34, 7, 10, 5, 69,
        109, 112, 116, 121, 98, 6, 112, 114, 111, 116, 111, 51,
    ]
    return out^

def empty_pb_proto_name() -> String:
    """Filename of `empty.proto` for gRPC reflection."""
    return String("empty.proto")

def empty_pb_reflection_symbols() -> List[String]:
    """Fully-qualified symbols declared in `empty.proto`."""
    var symbols: List[String] = [
        String("grpc.testing.Empty"),
    ]
    return symbols^
