# GENERATED by protoc-gen-mojo from messages.proto — do not edit.

"""Generated protobuf messages from `messages.proto`.

Regenerate with tools/protoc-gen-mojo; do not edit by hand.
"""

from proto import (
    WIRE_FIXED32,
    WIRE_FIXED64,
    WIRE_LEN,
    WIRE_VARINT,
    ProtoMessage,
    WireReader,
    WireWriter,
    zigzag_encode32,
    zigzag_encode64,
)


struct PayloadType:
    """Values of the `PayloadType` protobuf enum (fields carry `Int32`)."""

    comptime COMPRESSABLE = 0
    """`COMPRESSABLE` = 0."""


struct GrpclbRouteType:
    """Values of the `GrpclbRouteType` protobuf enum (fields carry `Int32`)."""

    comptime GRPCLB_ROUTE_TYPE_UNKNOWN = 0
    """`GRPCLB_ROUTE_TYPE_UNKNOWN` = 0."""
    comptime GRPCLB_ROUTE_TYPE_FALLBACK = 1
    """`GRPCLB_ROUTE_TYPE_FALLBACK` = 1."""
    comptime GRPCLB_ROUTE_TYPE_BACKEND = 2
    """`GRPCLB_ROUTE_TYPE_BACKEND` = 2."""


struct BoolValue(Copyable, Defaultable, Movable, ProtoMessage):
    """Generated from the `BoolValue` protobuf message."""

    var value: Bool
    """Field `value` (number 1)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.value = False
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.value:
            writer.bool_field(1, self.value)
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.value = reader.bool_value()
            else:
                reader.capture_field(field, wire_type, self._unknown)


struct Payload(Copyable, Defaultable, Movable, ProtoMessage):
    """Generated from the `Payload` protobuf message."""

    var type: Int32
    """Field `type` (number 1)."""
    var body: List[Byte]
    """Field `body` (number 2)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.type = 0
        self.body = List[Byte]()
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.type != 0:
            writer.int32(1, self.type)
        if len(self.body) != 0:
            writer.bytes_field(2, Span(self.body))
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.type = reader.int32_value()
            elif field == 2:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.body = reader.bytes_value()
            else:
                reader.capture_field(field, wire_type, self._unknown)


struct EchoStatus(Copyable, Defaultable, Movable, ProtoMessage):
    """Generated from the `EchoStatus` protobuf message."""

    var code: Int32
    """Field `code` (number 1)."""
    var message: String
    """Field `message` (number 2)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.code = 0
        self.message = String()
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.code != 0:
            writer.int32(1, self.code)
        if self.message.byte_length() != 0:
            writer.string_field(2, self.message)
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.code = reader.int32_value()
            elif field == 2:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.message = reader.string_value()
            else:
                reader.capture_field(field, wire_type, self._unknown)


struct SimpleRequest(Copyable, Defaultable, Movable, ProtoMessage):
    """Generated from the `SimpleRequest` protobuf message."""

    var response_type: Int32
    """Field `response_type` (number 1)."""
    var response_size: Int32
    """Field `response_size` (number 2)."""
    var payload: Optional[Payload]
    """Field `payload` (number 3)."""
    var fill_username: Bool
    """Field `fill_username` (number 4)."""
    var fill_oauth_scope: Bool
    """Field `fill_oauth_scope` (number 5)."""
    var response_compressed: Optional[BoolValue]
    """Field `response_compressed` (number 6)."""
    var response_status: Optional[EchoStatus]
    """Field `response_status` (number 7)."""
    var expect_compressed: Optional[BoolValue]
    """Field `expect_compressed` (number 8)."""
    var fill_server_id: Bool
    """Field `fill_server_id` (number 9)."""
    var fill_grpclb_route_type: Bool
    """Field `fill_grpclb_route_type` (number 10)."""
    var orca_per_query_report: Optional[TestOrcaReport]
    """Field `orca_per_query_report` (number 11)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.response_type = 0
        self.response_size = 0
        self.payload = None
        self.fill_username = False
        self.fill_oauth_scope = False
        self.response_compressed = None
        self.response_status = None
        self.expect_compressed = None
        self.fill_server_id = False
        self.fill_grpclb_route_type = False
        self.orca_per_query_report = None
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.response_type != 0:
            writer.int32(1, self.response_type)
        if self.response_size != 0:
            writer.int32(2, self.response_size)
        if self.payload:
            var sub = WireWriter()
            self.payload.value().encode_to(sub)
            writer.len_prefixed(3, Span(sub.buf))
        if self.fill_username:
            writer.bool_field(4, self.fill_username)
        if self.fill_oauth_scope:
            writer.bool_field(5, self.fill_oauth_scope)
        if self.response_compressed:
            var sub = WireWriter()
            self.response_compressed.value().encode_to(sub)
            writer.len_prefixed(6, Span(sub.buf))
        if self.response_status:
            var sub = WireWriter()
            self.response_status.value().encode_to(sub)
            writer.len_prefixed(7, Span(sub.buf))
        if self.expect_compressed:
            var sub = WireWriter()
            self.expect_compressed.value().encode_to(sub)
            writer.len_prefixed(8, Span(sub.buf))
        if self.fill_server_id:
            writer.bool_field(9, self.fill_server_id)
        if self.fill_grpclb_route_type:
            writer.bool_field(10, self.fill_grpclb_route_type)
        if self.orca_per_query_report:
            var sub = WireWriter()
            self.orca_per_query_report.value().encode_to(sub)
            writer.len_prefixed(11, Span(sub.buf))
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.response_type = reader.int32_value()
            elif field == 2:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.response_size = reader.int32_value()
            elif field == 3:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m: Payload
                    if self.payload:
                        m = self.payload.take()
                    else:
                        m = Payload()
                    m.merge_from(sub)
                    self.payload = m^
            elif field == 4:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.fill_username = reader.bool_value()
            elif field == 5:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.fill_oauth_scope = reader.bool_value()
            elif field == 6:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m: BoolValue
                    if self.response_compressed:
                        m = self.response_compressed.take()
                    else:
                        m = BoolValue()
                    m.merge_from(sub)
                    self.response_compressed = m^
            elif field == 7:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m: EchoStatus
                    if self.response_status:
                        m = self.response_status.take()
                    else:
                        m = EchoStatus()
                    m.merge_from(sub)
                    self.response_status = m^
            elif field == 8:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m: BoolValue
                    if self.expect_compressed:
                        m = self.expect_compressed.take()
                    else:
                        m = BoolValue()
                    m.merge_from(sub)
                    self.expect_compressed = m^
            elif field == 9:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.fill_server_id = reader.bool_value()
            elif field == 10:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.fill_grpclb_route_type = reader.bool_value()
            elif field == 11:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m: TestOrcaReport
                    if self.orca_per_query_report:
                        m = self.orca_per_query_report.take()
                    else:
                        m = TestOrcaReport()
                    m.merge_from(sub)
                    self.orca_per_query_report = m^
            else:
                reader.capture_field(field, wire_type, self._unknown)


struct SimpleResponse(Copyable, Defaultable, Movable, ProtoMessage):
    """Generated from the `SimpleResponse` protobuf message."""

    var payload: Optional[Payload]
    """Field `payload` (number 1)."""
    var username: String
    """Field `username` (number 2)."""
    var oauth_scope: String
    """Field `oauth_scope` (number 3)."""
    var server_id: String
    """Field `server_id` (number 4)."""
    var grpclb_route_type: Int32
    """Field `grpclb_route_type` (number 5)."""
    var hostname: String
    """Field `hostname` (number 6)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.payload = None
        self.username = String()
        self.oauth_scope = String()
        self.server_id = String()
        self.grpclb_route_type = 0
        self.hostname = String()
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.payload:
            var sub = WireWriter()
            self.payload.value().encode_to(sub)
            writer.len_prefixed(1, Span(sub.buf))
        if self.username.byte_length() != 0:
            writer.string_field(2, self.username)
        if self.oauth_scope.byte_length() != 0:
            writer.string_field(3, self.oauth_scope)
        if self.server_id.byte_length() != 0:
            writer.string_field(4, self.server_id)
        if self.grpclb_route_type != 0:
            writer.int32(5, self.grpclb_route_type)
        if self.hostname.byte_length() != 0:
            writer.string_field(6, self.hostname)
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m: Payload
                    if self.payload:
                        m = self.payload.take()
                    else:
                        m = Payload()
                    m.merge_from(sub)
                    self.payload = m^
            elif field == 2:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.username = reader.string_value()
            elif field == 3:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.oauth_scope = reader.string_value()
            elif field == 4:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.server_id = reader.string_value()
            elif field == 5:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.grpclb_route_type = reader.int32_value()
            elif field == 6:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.hostname = reader.string_value()
            else:
                reader.capture_field(field, wire_type, self._unknown)


struct StreamingInputCallRequest(Copyable, Defaultable, Movable, ProtoMessage):
    """Generated from the `StreamingInputCallRequest` protobuf message."""

    var payload: Optional[Payload]
    """Field `payload` (number 1)."""
    var expect_compressed: Optional[BoolValue]
    """Field `expect_compressed` (number 2)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.payload = None
        self.expect_compressed = None
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.payload:
            var sub = WireWriter()
            self.payload.value().encode_to(sub)
            writer.len_prefixed(1, Span(sub.buf))
        if self.expect_compressed:
            var sub = WireWriter()
            self.expect_compressed.value().encode_to(sub)
            writer.len_prefixed(2, Span(sub.buf))
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m: Payload
                    if self.payload:
                        m = self.payload.take()
                    else:
                        m = Payload()
                    m.merge_from(sub)
                    self.payload = m^
            elif field == 2:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m: BoolValue
                    if self.expect_compressed:
                        m = self.expect_compressed.take()
                    else:
                        m = BoolValue()
                    m.merge_from(sub)
                    self.expect_compressed = m^
            else:
                reader.capture_field(field, wire_type, self._unknown)


struct StreamingInputCallResponse(Copyable, Defaultable, Movable, ProtoMessage):
    """Generated from the `StreamingInputCallResponse` protobuf message."""

    var aggregated_payload_size: Int32
    """Field `aggregated_payload_size` (number 1)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.aggregated_payload_size = 0
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.aggregated_payload_size != 0:
            writer.int32(1, self.aggregated_payload_size)
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.aggregated_payload_size = reader.int32_value()
            else:
                reader.capture_field(field, wire_type, self._unknown)


struct ResponseParameters(Copyable, Defaultable, Movable, ProtoMessage):
    """Generated from the `ResponseParameters` protobuf message."""

    var size: Int32
    """Field `size` (number 1)."""
    var interval_us: Int32
    """Field `interval_us` (number 2)."""
    var compressed: Optional[BoolValue]
    """Field `compressed` (number 3)."""
    var fill_peer_socket_address: Optional[BoolValue]
    """Field `fill_peer_socket_address` (number 4)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.size = 0
        self.interval_us = 0
        self.compressed = None
        self.fill_peer_socket_address = None
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.size != 0:
            writer.int32(1, self.size)
        if self.interval_us != 0:
            writer.int32(2, self.interval_us)
        if self.compressed:
            var sub = WireWriter()
            self.compressed.value().encode_to(sub)
            writer.len_prefixed(3, Span(sub.buf))
        if self.fill_peer_socket_address:
            var sub = WireWriter()
            self.fill_peer_socket_address.value().encode_to(sub)
            writer.len_prefixed(4, Span(sub.buf))
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.size = reader.int32_value()
            elif field == 2:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.interval_us = reader.int32_value()
            elif field == 3:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m: BoolValue
                    if self.compressed:
                        m = self.compressed.take()
                    else:
                        m = BoolValue()
                    m.merge_from(sub)
                    self.compressed = m^
            elif field == 4:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m: BoolValue
                    if self.fill_peer_socket_address:
                        m = self.fill_peer_socket_address.take()
                    else:
                        m = BoolValue()
                    m.merge_from(sub)
                    self.fill_peer_socket_address = m^
            else:
                reader.capture_field(field, wire_type, self._unknown)


struct StreamingOutputCallRequest(Copyable, Defaultable, Movable, ProtoMessage):
    """Generated from the `StreamingOutputCallRequest` protobuf message."""

    var response_type: Int32
    """Field `response_type` (number 1)."""
    var response_parameters: List[ResponseParameters]
    """Field `response_parameters` (number 2, repeated)."""
    var payload: Optional[Payload]
    """Field `payload` (number 3)."""
    var response_status: Optional[EchoStatus]
    """Field `response_status` (number 7)."""
    var orca_oob_report: Optional[TestOrcaReport]
    """Field `orca_oob_report` (number 8)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.response_type = 0
        self.response_parameters = List[ResponseParameters]()
        self.payload = None
        self.response_status = None
        self.orca_oob_report = None
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.response_type != 0:
            writer.int32(1, self.response_type)
        for v in self.response_parameters:
            var sub = WireWriter()
            v.encode_to(sub)
            writer.len_prefixed(2, Span(sub.buf))
        if self.payload:
            var sub = WireWriter()
            self.payload.value().encode_to(sub)
            writer.len_prefixed(3, Span(sub.buf))
        if self.response_status:
            var sub = WireWriter()
            self.response_status.value().encode_to(sub)
            writer.len_prefixed(7, Span(sub.buf))
        if self.orca_oob_report:
            var sub = WireWriter()
            self.orca_oob_report.value().encode_to(sub)
            writer.len_prefixed(8, Span(sub.buf))
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.response_type = reader.int32_value()
            elif field == 2:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m = ResponseParameters()
                    m.merge_from(sub)
                    self.response_parameters.append(m^)
            elif field == 3:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m: Payload
                    if self.payload:
                        m = self.payload.take()
                    else:
                        m = Payload()
                    m.merge_from(sub)
                    self.payload = m^
            elif field == 7:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m: EchoStatus
                    if self.response_status:
                        m = self.response_status.take()
                    else:
                        m = EchoStatus()
                    m.merge_from(sub)
                    self.response_status = m^
            elif field == 8:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m: TestOrcaReport
                    if self.orca_oob_report:
                        m = self.orca_oob_report.take()
                    else:
                        m = TestOrcaReport()
                    m.merge_from(sub)
                    self.orca_oob_report = m^
            else:
                reader.capture_field(field, wire_type, self._unknown)


struct StreamingOutputCallResponse(
    Copyable, Defaultable, Movable, ProtoMessage
):
    """Generated from the `StreamingOutputCallResponse` protobuf message."""

    var payload: Optional[Payload]
    """Field `payload` (number 1)."""
    var peer_socket_address: String
    """Field `peer_socket_address` (number 2)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.payload = None
        self.peer_socket_address = String()
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.payload:
            var sub = WireWriter()
            self.payload.value().encode_to(sub)
            writer.len_prefixed(1, Span(sub.buf))
        if self.peer_socket_address.byte_length() != 0:
            writer.string_field(2, self.peer_socket_address)
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m: Payload
                    if self.payload:
                        m = self.payload.take()
                    else:
                        m = Payload()
                    m.merge_from(sub)
                    self.payload = m^
            elif field == 2:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.peer_socket_address = reader.string_value()
            else:
                reader.capture_field(field, wire_type, self._unknown)


struct ReconnectParams(Copyable, Defaultable, Movable, ProtoMessage):
    """Generated from the `ReconnectParams` protobuf message."""

    var max_reconnect_backoff_ms: Int32
    """Field `max_reconnect_backoff_ms` (number 1)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.max_reconnect_backoff_ms = 0
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.max_reconnect_backoff_ms != 0:
            writer.int32(1, self.max_reconnect_backoff_ms)
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.max_reconnect_backoff_ms = reader.int32_value()
            else:
                reader.capture_field(field, wire_type, self._unknown)


struct ReconnectInfo(Copyable, Defaultable, Movable, ProtoMessage):
    """Generated from the `ReconnectInfo` protobuf message."""

    var passed: Bool
    """Field `passed` (number 1)."""
    var backoff_ms: List[Int32]
    """Field `backoff_ms` (number 2, repeated)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.passed = False
        self.backoff_ms = List[Int32]()
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.passed:
            writer.bool_field(1, self.passed)
        if len(self.backoff_ms) != 0:
            var sub = WireWriter()
            for v in self.backoff_ms:
                sub.varint(UInt64(Int64(v)))
            writer.len_prefixed(2, Span(sub.buf))
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.passed = reader.bool_value()
            elif field == 2:
                if wire_type == WIRE_LEN:
                    var sub = reader.sub_reader()
                    while not sub.done():
                        self.backoff_ms.append(sub.int32_value())
                elif wire_type == WIRE_VARINT:
                    self.backoff_ms.append(reader.int32_value())
                else:
                    reader.capture_field(field, wire_type, self._unknown)
            else:
                reader.capture_field(field, wire_type, self._unknown)


struct LoadBalancerStatsRequest(Copyable, Defaultable, Movable, ProtoMessage):
    """Generated from the `LoadBalancerStatsRequest` protobuf message."""

    var num_rpcs: Int32
    """Field `num_rpcs` (number 1)."""
    var timeout_sec: Int32
    """Field `timeout_sec` (number 2)."""
    var metadata_keys: List[String]
    """Field `metadata_keys` (number 3, repeated)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.num_rpcs = 0
        self.timeout_sec = 0
        self.metadata_keys = List[String]()
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.num_rpcs != 0:
            writer.int32(1, self.num_rpcs)
        if self.timeout_sec != 0:
            writer.int32(2, self.timeout_sec)
        for v in self.metadata_keys:
            writer.string_field(3, v)
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.num_rpcs = reader.int32_value()
            elif field == 2:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.timeout_sec = reader.int32_value()
            elif field == 3:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.metadata_keys.append(reader.string_value())
            else:
                reader.capture_field(field, wire_type, self._unknown)


struct LoadBalancerStatsResponse_MetadataType:
    """Values of the `MetadataType` protobuf enum (fields carry `Int32`)."""

    comptime UNKNOWN = 0
    """`UNKNOWN` = 0."""
    comptime INITIAL = 1
    """`INITIAL` = 1."""
    comptime TRAILING = 2
    """`TRAILING` = 2."""


struct LoadBalancerStatsResponse_MetadataEntry(
    Copyable, Defaultable, Movable, ProtoMessage
):
    """Generated from the `MetadataEntry` protobuf message."""

    var key: String
    """Field `key` (number 1)."""
    var value: String
    """Field `value` (number 2)."""
    var type: Int32
    """Field `type` (number 3)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.key = String()
        self.value = String()
        self.type = 0
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.key.byte_length() != 0:
            writer.string_field(1, self.key)
        if self.value.byte_length() != 0:
            writer.string_field(2, self.value)
        if self.type != 0:
            writer.int32(3, self.type)
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.key = reader.string_value()
            elif field == 2:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.value = reader.string_value()
            elif field == 3:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.type = reader.int32_value()
            else:
                reader.capture_field(field, wire_type, self._unknown)


struct LoadBalancerStatsResponse_RpcMetadata(
    Copyable, Defaultable, Movable, ProtoMessage
):
    """Generated from the `RpcMetadata` protobuf message."""

    var metadata: List[LoadBalancerStatsResponse_MetadataEntry]
    """Field `metadata` (number 1, repeated)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.metadata = List[LoadBalancerStatsResponse_MetadataEntry]()
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        for v in self.metadata:
            var sub = WireWriter()
            v.encode_to(sub)
            writer.len_prefixed(1, Span(sub.buf))
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m = LoadBalancerStatsResponse_MetadataEntry()
                    m.merge_from(sub)
                    self.metadata.append(m^)
            else:
                reader.capture_field(field, wire_type, self._unknown)


struct LoadBalancerStatsResponse_MetadataByPeer(
    Copyable, Defaultable, Movable, ProtoMessage
):
    """Generated from the `MetadataByPeer` protobuf message."""

    var rpc_metadata: List[LoadBalancerStatsResponse_RpcMetadata]
    """Field `rpc_metadata` (number 1, repeated)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.rpc_metadata = List[LoadBalancerStatsResponse_RpcMetadata]()
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        for v in self.rpc_metadata:
            var sub = WireWriter()
            v.encode_to(sub)
            writer.len_prefixed(1, Span(sub.buf))
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m = LoadBalancerStatsResponse_RpcMetadata()
                    m.merge_from(sub)
                    self.rpc_metadata.append(m^)
            else:
                reader.capture_field(field, wire_type, self._unknown)


struct LoadBalancerStatsResponse_RpcsByPeer(
    Copyable, Defaultable, Movable, ProtoMessage
):
    """Generated from the `RpcsByPeer` protobuf message."""

    var rpcs_by_peer: Dict[String, Int32]
    """Field `rpcs_by_peer` (number 1, map field)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.rpcs_by_peer = Dict[String, Int32]()
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        for entry in self.rpcs_by_peer.items():
            var sub = WireWriter()
            if entry.key.byte_length() != 0:
                sub.string_field(1, entry.key)
            if entry.value != 0:
                sub.int32(2, entry.value)
            writer.len_prefixed(1, Span(sub.buf))
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var key: String = String()
                    var value: Int32 = 0
                    while not sub.done():
                        var etag = sub.read_tag()
                        if etag[0] == 1:
                            key = sub.string_value()
                        elif etag[0] == 2:
                            value = sub.int32_value()
                        else:
                            sub.skip(etag[1])
                    self.rpcs_by_peer[key^] = value
            else:
                reader.capture_field(field, wire_type, self._unknown)


struct LoadBalancerStatsResponse(Copyable, Defaultable, Movable, ProtoMessage):
    """Generated from the `LoadBalancerStatsResponse` protobuf message."""

    var rpcs_by_peer: Dict[String, Int32]
    """Field `rpcs_by_peer` (number 1, map field)."""
    var num_failures: Int32
    """Field `num_failures` (number 2)."""
    var rpcs_by_method: Dict[String, LoadBalancerStatsResponse_RpcsByPeer]
    """Field `rpcs_by_method` (number 3, map field)."""
    var metadatas_by_peer: Dict[
        String, LoadBalancerStatsResponse_MetadataByPeer
    ]
    """Field `metadatas_by_peer` (number 4, map field)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.rpcs_by_peer = Dict[String, Int32]()
        self.num_failures = 0
        self.rpcs_by_method = Dict[
            String, LoadBalancerStatsResponse_RpcsByPeer
        ]()
        self.metadatas_by_peer = Dict[
            String, LoadBalancerStatsResponse_MetadataByPeer
        ]()
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        for entry in self.rpcs_by_peer.items():
            var sub = WireWriter()
            if entry.key.byte_length() != 0:
                sub.string_field(1, entry.key)
            if entry.value != 0:
                sub.int32(2, entry.value)
            writer.len_prefixed(1, Span(sub.buf))
        if self.num_failures != 0:
            writer.int32(2, self.num_failures)
        for entry in self.rpcs_by_method.items():
            var sub = WireWriter()
            if entry.key.byte_length() != 0:
                sub.string_field(1, entry.key)
            var vsub = WireWriter()
            entry.value.encode_to(vsub)
            sub.len_prefixed(2, Span(vsub.buf))
            writer.len_prefixed(3, Span(sub.buf))
        for entry in self.metadatas_by_peer.items():
            var sub = WireWriter()
            if entry.key.byte_length() != 0:
                sub.string_field(1, entry.key)
            var vsub = WireWriter()
            entry.value.encode_to(vsub)
            sub.len_prefixed(2, Span(vsub.buf))
            writer.len_prefixed(4, Span(sub.buf))
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var key: String = String()
                    var value: Int32 = 0
                    while not sub.done():
                        var etag = sub.read_tag()
                        if etag[0] == 1:
                            key = sub.string_value()
                        elif etag[0] == 2:
                            value = sub.int32_value()
                        else:
                            sub.skip(etag[1])
                    self.rpcs_by_peer[key^] = value
            elif field == 2:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.num_failures = reader.int32_value()
            elif field == 3:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var key: String = String()
                    var value: LoadBalancerStatsResponse_RpcsByPeer = (
                        LoadBalancerStatsResponse_RpcsByPeer()
                    )
                    while not sub.done():
                        var etag = sub.read_tag()
                        if etag[0] == 1:
                            key = sub.string_value()
                        elif etag[0] == 2:
                            var msub = sub.sub_reader()
                            value.merge_from(msub)
                        else:
                            sub.skip(etag[1])
                    self.rpcs_by_method[key^] = value^
            elif field == 4:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var key: String = String()
                    var value: LoadBalancerStatsResponse_MetadataByPeer = (
                        LoadBalancerStatsResponse_MetadataByPeer()
                    )
                    while not sub.done():
                        var etag = sub.read_tag()
                        if etag[0] == 1:
                            key = sub.string_value()
                        elif etag[0] == 2:
                            var msub = sub.sub_reader()
                            value.merge_from(msub)
                        else:
                            sub.skip(etag[1])
                    self.metadatas_by_peer[key^] = value^
            else:
                reader.capture_field(field, wire_type, self._unknown)


struct LoadBalancerAccumulatedStatsRequest(
    Copyable, Defaultable, Movable, ProtoMessage
):
    """Generated from the `LoadBalancerAccumulatedStatsRequest` protobuf message.
    """

    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes an empty message."""
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Args:
            writer: Destination wire-format writer.
        """
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            reader.capture_field(tag[0], tag[1], self._unknown)


struct LoadBalancerAccumulatedStatsResponse_MethodStats(
    Copyable, Defaultable, Movable, ProtoMessage
):
    """Generated from the `MethodStats` protobuf message."""

    var rpcs_started: Int32
    """Field `rpcs_started` (number 1)."""
    var result: Dict[Int32, Int32]
    """Field `result` (number 2, map field)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.rpcs_started = 0
        self.result = Dict[Int32, Int32]()
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.rpcs_started != 0:
            writer.int32(1, self.rpcs_started)
        for entry in self.result.items():
            var sub = WireWriter()
            if entry.key != 0:
                sub.int32(1, entry.key)
            if entry.value != 0:
                sub.int32(2, entry.value)
            writer.len_prefixed(2, Span(sub.buf))
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.rpcs_started = reader.int32_value()
            elif field == 2:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var key: Int32 = 0
                    var value: Int32 = 0
                    while not sub.done():
                        var etag = sub.read_tag()
                        if etag[0] == 1:
                            key = sub.int32_value()
                        elif etag[0] == 2:
                            value = sub.int32_value()
                        else:
                            sub.skip(etag[1])
                    self.result[key] = value
            else:
                reader.capture_field(field, wire_type, self._unknown)


struct LoadBalancerAccumulatedStatsResponse(
    Copyable, Defaultable, Movable, ProtoMessage
):
    """Generated from the `LoadBalancerAccumulatedStatsResponse` protobuf message.
    """

    var num_rpcs_started_by_method: Dict[String, Int32]
    """Field `num_rpcs_started_by_method` (number 1, map field)."""
    var num_rpcs_succeeded_by_method: Dict[String, Int32]
    """Field `num_rpcs_succeeded_by_method` (number 2, map field)."""
    var num_rpcs_failed_by_method: Dict[String, Int32]
    """Field `num_rpcs_failed_by_method` (number 3, map field)."""
    var stats_per_method: Dict[
        String, LoadBalancerAccumulatedStatsResponse_MethodStats
    ]
    """Field `stats_per_method` (number 4, map field)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.num_rpcs_started_by_method = Dict[String, Int32]()
        self.num_rpcs_succeeded_by_method = Dict[String, Int32]()
        self.num_rpcs_failed_by_method = Dict[String, Int32]()
        self.stats_per_method = Dict[
            String, LoadBalancerAccumulatedStatsResponse_MethodStats
        ]()
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        for entry in self.num_rpcs_started_by_method.items():
            var sub = WireWriter()
            if entry.key.byte_length() != 0:
                sub.string_field(1, entry.key)
            if entry.value != 0:
                sub.int32(2, entry.value)
            writer.len_prefixed(1, Span(sub.buf))
        for entry in self.num_rpcs_succeeded_by_method.items():
            var sub = WireWriter()
            if entry.key.byte_length() != 0:
                sub.string_field(1, entry.key)
            if entry.value != 0:
                sub.int32(2, entry.value)
            writer.len_prefixed(2, Span(sub.buf))
        for entry in self.num_rpcs_failed_by_method.items():
            var sub = WireWriter()
            if entry.key.byte_length() != 0:
                sub.string_field(1, entry.key)
            if entry.value != 0:
                sub.int32(2, entry.value)
            writer.len_prefixed(3, Span(sub.buf))
        for entry in self.stats_per_method.items():
            var sub = WireWriter()
            if entry.key.byte_length() != 0:
                sub.string_field(1, entry.key)
            var vsub = WireWriter()
            entry.value.encode_to(vsub)
            sub.len_prefixed(2, Span(vsub.buf))
            writer.len_prefixed(4, Span(sub.buf))
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var key: String = String()
                    var value: Int32 = 0
                    while not sub.done():
                        var etag = sub.read_tag()
                        if etag[0] == 1:
                            key = sub.string_value()
                        elif etag[0] == 2:
                            value = sub.int32_value()
                        else:
                            sub.skip(etag[1])
                    self.num_rpcs_started_by_method[key^] = value
            elif field == 2:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var key: String = String()
                    var value: Int32 = 0
                    while not sub.done():
                        var etag = sub.read_tag()
                        if etag[0] == 1:
                            key = sub.string_value()
                        elif etag[0] == 2:
                            value = sub.int32_value()
                        else:
                            sub.skip(etag[1])
                    self.num_rpcs_succeeded_by_method[key^] = value
            elif field == 3:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var key: String = String()
                    var value: Int32 = 0
                    while not sub.done():
                        var etag = sub.read_tag()
                        if etag[0] == 1:
                            key = sub.string_value()
                        elif etag[0] == 2:
                            value = sub.int32_value()
                        else:
                            sub.skip(etag[1])
                    self.num_rpcs_failed_by_method[key^] = value
            elif field == 4:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var key: String = String()
                    var value: LoadBalancerAccumulatedStatsResponse_MethodStats = (
                        LoadBalancerAccumulatedStatsResponse_MethodStats()
                    )
                    while not sub.done():
                        var etag = sub.read_tag()
                        if etag[0] == 1:
                            key = sub.string_value()
                        elif etag[0] == 2:
                            var msub = sub.sub_reader()
                            value.merge_from(msub)
                        else:
                            sub.skip(etag[1])
                    self.stats_per_method[key^] = value^
            else:
                reader.capture_field(field, wire_type, self._unknown)


struct ClientConfigureRequest_RpcType:
    """Values of the `RpcType` protobuf enum (fields carry `Int32`)."""

    comptime EMPTY_CALL = 0
    """`EMPTY_CALL` = 0."""
    comptime UNARY_CALL = 1
    """`UNARY_CALL` = 1."""


struct ClientConfigureRequest_Metadata(
    Copyable, Defaultable, Movable, ProtoMessage
):
    """Generated from the `Metadata` protobuf message."""

    var type: Int32
    """Field `type` (number 1)."""
    var key: String
    """Field `key` (number 2)."""
    var value: String
    """Field `value` (number 3)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.type = 0
        self.key = String()
        self.value = String()
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.type != 0:
            writer.int32(1, self.type)
        if self.key.byte_length() != 0:
            writer.string_field(2, self.key)
        if self.value.byte_length() != 0:
            writer.string_field(3, self.value)
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.type = reader.int32_value()
            elif field == 2:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.key = reader.string_value()
            elif field == 3:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.value = reader.string_value()
            else:
                reader.capture_field(field, wire_type, self._unknown)


struct ClientConfigureRequest(Copyable, Defaultable, Movable, ProtoMessage):
    """Generated from the `ClientConfigureRequest` protobuf message."""

    var types: List[Int32]
    """Field `types` (number 1, repeated)."""
    var metadata: List[ClientConfigureRequest_Metadata]
    """Field `metadata` (number 2, repeated)."""
    var timeout_sec: Int32
    """Field `timeout_sec` (number 3)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.types = List[Int32]()
        self.metadata = List[ClientConfigureRequest_Metadata]()
        self.timeout_sec = 0
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if len(self.types) != 0:
            var sub = WireWriter()
            for v in self.types:
                sub.varint(UInt64(Int64(v)))
            writer.len_prefixed(1, Span(sub.buf))
        for v in self.metadata:
            var sub = WireWriter()
            v.encode_to(sub)
            writer.len_prefixed(2, Span(sub.buf))
        if self.timeout_sec != 0:
            writer.int32(3, self.timeout_sec)
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type == WIRE_LEN:
                    var sub = reader.sub_reader()
                    while not sub.done():
                        self.types.append(sub.int32_value())
                elif wire_type == WIRE_VARINT:
                    self.types.append(reader.int32_value())
                else:
                    reader.capture_field(field, wire_type, self._unknown)
            elif field == 2:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var m = ClientConfigureRequest_Metadata()
                    m.merge_from(sub)
                    self.metadata.append(m^)
            elif field == 3:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.timeout_sec = reader.int32_value()
            else:
                reader.capture_field(field, wire_type, self._unknown)


struct ClientConfigureResponse(Copyable, Defaultable, Movable, ProtoMessage):
    """Generated from the `ClientConfigureResponse` protobuf message."""

    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes an empty message."""
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Args:
            writer: Destination wire-format writer.
        """
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            reader.capture_field(tag[0], tag[1], self._unknown)


struct MemorySize(Copyable, Defaultable, Movable, ProtoMessage):
    """Generated from the `MemorySize` protobuf message."""

    var rss: Int64
    """Field `rss` (number 1)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.rss = 0
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.rss != 0:
            writer.int64(1, self.rss)
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.rss = reader.int64_value()
            else:
                reader.capture_field(field, wire_type, self._unknown)


struct TestOrcaReport(Copyable, Defaultable, Movable, ProtoMessage):
    """Generated from the `TestOrcaReport` protobuf message."""

    var cpu_utilization: Float64
    """Field `cpu_utilization` (number 1)."""
    var memory_utilization: Float64
    """Field `memory_utilization` (number 2)."""
    var request_cost: Dict[String, Float64]
    """Field `request_cost` (number 3, map field)."""
    var utilization: Dict[String, Float64]
    """Field `utilization` (number 4, map field)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.cpu_utilization = 0.0
        self.memory_utilization = 0.0
        self.request_cost = Dict[String, Float64]()
        self.utilization = Dict[String, Float64]()
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.cpu_utilization != 0.0:
            writer.double_field(1, self.cpu_utilization)
        if self.memory_utilization != 0.0:
            writer.double_field(2, self.memory_utilization)
        for entry in self.request_cost.items():
            var sub = WireWriter()
            if entry.key.byte_length() != 0:
                sub.string_field(1, entry.key)
            if entry.value != 0.0:
                sub.double_field(2, entry.value)
            writer.len_prefixed(3, Span(sub.buf))
        for entry in self.utilization.items():
            var sub = WireWriter()
            if entry.key.byte_length() != 0:
                sub.string_field(1, entry.key)
            if entry.value != 0.0:
                sub.double_field(2, entry.value)
            writer.len_prefixed(4, Span(sub.buf))
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_FIXED64:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.cpu_utilization = reader.double_value()
            elif field == 2:
                if wire_type != WIRE_FIXED64:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.memory_utilization = reader.double_value()
            elif field == 3:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var key: String = String()
                    var value: Float64 = 0.0
                    while not sub.done():
                        var etag = sub.read_tag()
                        if etag[0] == 1:
                            key = sub.string_value()
                        elif etag[0] == 2:
                            value = sub.double_value()
                        else:
                            sub.skip(etag[1])
                    self.request_cost[key^] = value
            elif field == 4:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    var sub = reader.sub_reader()
                    var key: String = String()
                    var value: Float64 = 0.0
                    while not sub.done():
                        var etag = sub.read_tag()
                        if etag[0] == 1:
                            key = sub.string_value()
                        elif etag[0] == 2:
                            value = sub.double_value()
                        else:
                            sub.skip(etag[1])
                    self.utilization[key^] = value
            else:
                reader.capture_field(field, wire_type, self._unknown)


struct SetReturnStatusRequest(Copyable, Defaultable, Movable, ProtoMessage):
    """Generated from the `SetReturnStatusRequest` protobuf message."""

    var grpc_code_to_return: Int32
    """Field `grpc_code_to_return` (number 1)."""
    var grpc_status_description: String
    """Field `grpc_status_description` (number 2)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.grpc_code_to_return = 0
        self.grpc_status_description = String()
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.grpc_code_to_return != 0:
            writer.int32(1, self.grpc_code_to_return)
        if self.grpc_status_description.byte_length() != 0:
            writer.string_field(2, self.grpc_status_description)
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.grpc_code_to_return = reader.int32_value()
            elif field == 2:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.grpc_status_description = reader.string_value()
            else:
                reader.capture_field(field, wire_type, self._unknown)


struct HookRequest_HookRequestCommand:
    """Values of the `HookRequestCommand` protobuf enum (fields carry `Int32`).
    """

    comptime UNSPECIFIED = 0
    """`UNSPECIFIED` = 0."""
    comptime START = 1
    """`START` = 1."""
    comptime STOP = 2
    """`STOP` = 2."""
    comptime RETURN = 3
    """`RETURN` = 3."""


struct HookRequest(Copyable, Defaultable, Movable, ProtoMessage):
    """Generated from the `HookRequest` protobuf message."""

    var command: Int32
    """Field `command` (number 1)."""
    var grpc_code_to_return: Int32
    """Field `grpc_code_to_return` (number 2)."""
    var grpc_status_description: String
    """Field `grpc_status_description` (number 3)."""
    var server_port: Int32
    """Field `server_port` (number 4)."""
    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes all fields to their proto3 defaults."""
        self.command = 0
        self.grpc_code_to_return = 0
        self.grpc_status_description = String()
        self.server_port = 0
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Fields set to their proto3 default are omitted; preserved
        unknown fields are re-emitted at the end.

        Args:
            writer: Destination wire-format writer.
        """
        if self.command != 0:
            writer.int32(1, self.command)
        if self.grpc_code_to_return != 0:
            writer.int32(2, self.grpc_code_to_return)
        if self.grpc_status_description.byte_length() != 0:
            writer.string_field(3, self.grpc_status_description)
        if self.server_port != 0:
            writer.int32(4, self.server_port)
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Later singular values overwrite earlier ones, repeated fields
        append, submessages merge, and unknown fields are preserved.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.command = reader.int32_value()
            elif field == 2:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.grpc_code_to_return = reader.int32_value()
            elif field == 3:
                if wire_type != WIRE_LEN:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.grpc_status_description = reader.string_value()
            elif field == 4:
                if wire_type != WIRE_VARINT:
                    reader.capture_field(field, wire_type, self._unknown)
                else:
                    self.server_port = reader.int32_value()
            else:
                reader.capture_field(field, wire_type, self._unknown)


struct HookResponse(Copyable, Defaultable, Movable, ProtoMessage):
    """Generated from the `HookResponse` protobuf message."""

    var _unknown: List[Byte]
    """Preserved unknown fields, re-emitted on encode."""

    def __init__(out self):
        """Initializes an empty message."""
        self._unknown = List[Byte]()

    def encode_to(self, mut writer: WireWriter):
        """Appends the wire-format bytes to the writer.

        Args:
            writer: Destination wire-format writer.
        """
        writer.buf.extend(Span(self._unknown))

    def merge_from(mut self, mut reader: WireReader) raises:
        """Merges fields decoded from the reader into this message.

        Args:
            reader: Source wire-format reader.

        Raises:
            Error: If the input is not valid protobuf wire data.
        """
        while not reader.done():
            var tag = reader.read_tag()
            reader.capture_field(tag[0], tag[1], self._unknown)
