# GENERATED by protoc-gen-mojo from echo.proto — do not edit.

from proto import (
    WIRE_LEN,
    WIRE_VARINT,
    ProtoMessage,
    WireReader,
    WireWriter,
    zigzag_encode32,
    zigzag_encode64,
)
from grpc import GrpcChannel


struct EchoRequest(Copyable, Defaultable, Movable, ProtoMessage):
    var message: String  # 1

    def __init__(out self):
        self.message = String()

    def encode_to(self, mut writer: WireWriter):
        if self.message.byte_length() != 0:
            writer.string_field(1, self.message)

    def merge_from(mut self, mut reader: WireReader) raises:
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                self.message = reader.string_value()
            else:
                reader.skip(wire_type)


struct EchoResponse(Copyable, Defaultable, Movable, ProtoMessage):
    var message: String  # 1

    def __init__(out self):
        self.message = String()

    def encode_to(self, mut writer: WireWriter):
        if self.message.byte_length() != 0:
            writer.string_field(1, self.message)

    def merge_from(mut self, mut reader: WireReader) raises:
        while not reader.done():
            var tag = reader.read_tag()
            var field = tag[0]
            var wire_type = tag[1]
            if field == 1:
                self.message = reader.string_value()
            else:
                reader.skip(wire_type)


comptime ECHO_SAY_PATH = "/echo.Echo/Say"


@fieldwise_init
struct EchoClient(Movable):
    """Generated unary client for echo.Echo."""

    var channel: GrpcChannel

    @staticmethod
    def connect(host: StringSpan, port: UInt16) raises -> EchoClient:
        return EchoClient(channel=GrpcChannel.connect(host, port))

    def say(
        mut self, request: EchoRequest, *, timeout_ns: Int64 = 0
    ) raises -> EchoResponse:
        return self.channel.unary[EchoRequest, EchoResponse](
            ECHO_SAY_PATH, request, timeout_ns=timeout_ns
        )

    def close(mut self):
        self.channel.close()
