#!/usr/bin/env python3
"""Require a single generated compliance report in docs/."""

import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
REPORT_NAMES = ("COMPLIANCE.md", "COMPLIANCE.html")
GENERATED_MARKER = "GENERATED by test/compliance/run_compliance.py"


def check_report_layout(root: Path) -> list[str]:
    """Return problems with the canonical report layout under root."""
    problems: list[str] = []
    for name in REPORT_NAMES:
        canonical = root / "docs" / name
        legacy = root / name

        if not canonical.is_file():
            problems.append(f"missing canonical report: {canonical.relative_to(root)}")
        elif GENERATED_MARKER not in canonical.read_text():
            problems.append(
                f"canonical report is not generated: {canonical.relative_to(root)}"
            )

        if legacy.exists():
            relation = "duplicates"
            if canonical.is_file() and legacy.read_bytes() != canonical.read_bytes():
                relation = "differs from"
            problems.append(
                f"legacy report {legacy.relative_to(root)} {relation} "
                f"{canonical.relative_to(root)}; remove the legacy copy"
            )

    return problems


def main() -> int:
    problems = check_report_layout(ROOT)
    if problems:
        for problem in problems:
            print(f"ERROR: {problem}", file=sys.stderr)
        return 1

    print("PASS canonical compliance report layout")
    return 0


if __name__ == "__main__":
    sys.exit(main())
